version: 2.1

jobs:
  py37:
    working_directory: ~/torchdyn_test_suite
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            python -c "req = open('requirements.txt').read().replace('>', '=') ; open('requirements.txt', 'w').write(req)"
            sudo python -m pip install --upgrade --user pip
            sudo pip install -r requirements.txt 
            sudo python setup.py install
      - run:
          command: |
            python test/test_neural_de.py
            python test/test_ode_adjoint.py
            python test/test_flows.py    

  py38:
    working_directory: ~/torchdyn_test_suite
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            python -c "req = open('requirements.txt').read().replace('>', '=') ; open('requirements.txt', 'w').write(req)"
            sudo python -m pip install --upgrade --user pip
            sudo pip install -r requirements.txt 
            sudo python setup.py install
      - run:
          command: |
            python test/test_neural_de.py
            python test/test_ode_adjoint.py
            python test/test_flows.py 
            
  py39:
    working_directory: ~/torchdyn_test_suite
    docker:
      - image: circleci/python:3.9.0a1
    steps:
      - checkout
      - run:
          command: |
            python -c "req = open('requirements.txt').read().replace('>', '=') ; open('requirements.txt', 'w').write(req)"
            sudo python -m pip install --upgrade --user pip
            sudo pip install -r requirements.txt 
            sudo python setup.py install
      - run:
          command: |
            python test/test_neural_de.py
            python test/test_ode_adjoint.py
            python test/test_flows.py 
            
  cov:
    working_directory: ~/torchdyn_test_suite
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            python -c "req = open('requirements.txt').read().replace('>', '=') ; open('requirements.txt', 'w').write(req)"
            sudo python -m pip install --upgrade --user pip
            sudo pip install -r requirements.txt 
            sudo python setup.py install
      - run:
          command: |
            pip install codecov
            codecov run test/test_neural_de.py
            codecov run test/test_ode_adjoint.py
            codecov run test/test_flows.py 
            
workflows:
  version: 1
  python_linux:
    jobs:
      - py37
      - py38
      - cov
