version: 2.1

jobs:
  py37:
    working_directory: ~/torchdyn
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            python -c "req = open('requirements/base.txt').read().replace('>', '=') ; open('requirements.txt', 'w').write(req)"
            sudo python -m pip install --upgrade --user pip
            sudo pip install -r requirements/base.txt
            sudo pip install -r requirements/external.txt
            sudo python setup.py install
            sudo pip install pytest pytest-cov
      - run:
          command: |
            pip install codecov
            pytest --cov=./
            codecov

  py38:
    working_directory: ~/torchdyn
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            python -c "req = open('requirements/base.txt').read().replace('>', '=') ; open('requirements.txt', 'w').write(req)"
            sudo python -m pip install --upgrade --user pip
            sudo pip install -r requirements/base.txt
            sudo pip install -r requirements/external.txt
            sudo python setup.py install
            sudo pip install pytest pytest-cov
      - run:
          command: |
            pip install codecov
            pytest --cov=torchdyn
            codecov

  py39:
    working_directory: ~/torchdyn
    docker:
      - image: circleci/python:3.9.0a1
    steps:
      - checkout
      - run:
          command: |
            python -c "req = open('requirements/base.txt').read().replace('>', '=') ; open('requirements.txt', 'w').write(req)"
            sudo python -m pip install --upgrade --user pip
            sudo pip install -r requirements/base.txt
            sudo pip install -r requirements/external.txt
            sudo pip install pytest pytest-cov
      - run:
          command: |
            pip install codecov
            pytest --cov=torchdyn
            codecov

  cov:
    working_directory: ~/torchdyn_test
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            python -c "req = open('requirements/base.txt').read().replace('>', '=') ; open('requirements.txt', 'w').write(req)"
            sudo python -m pip install --upgrade --user pip
            sudo pip install -r requirements/base.txt
            sudo pip install -r requirements/external.txt
            sudo pip install pytest pytest-cov
            sudo python setup.py install
            pip install codecov
            pip install coverage
      - run:
          command: |
            coverage run --source=torchdyn -m pytest
            codecov

workflows:
  version: 1
  python_linux:
    jobs:
      - cov
