name: PyPI Release with Poetry

on:
  release:
    types:
      - created
      - edited

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - 
        source $HOME/.poetry/env
        poetry lock
        poetry build

    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
      run: |
        source $HOME/.poetry/env
        poetry config pypi-token.pypi ${{ secrets.pypi_token }}
        poetry publish
