name: PyPI Release with Poetry

on:
  release:
    types:
      - created
      - edited

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8
    # see https://github.com/python-poetry/poetry/issues/6377
    - name: Build
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/901bdf0491005f1b3db41947d0d938da6838ecb9/get-poetry.py | python - 
        source $HOME/.poetry/env
        poetry lock
        poetry build

    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
      run: |
        source $HOME/.poetry/env
        poetry config pypi-token.pypi ${{ secrets.pypi_token }}
        poetry publish
